[13.0] [FIX] cmis_field: empty cmis folder when cleaning up folder
acsone/alfodoo pull request #155
Opened 2022-02-25 12:26 UTC by ThomasBinsfeld

If an error is raised just after the creation of the cmis folder, in the same transaction, the rollback hook deletes the folder in Alfresco but the cmis field of the record is not emptied. Leaving us with a record referencing a non-existing folder.

Here i empty the cmis folder reference after deleting the Alfresco folder.

I just don't get why the rollback is not enough.

2022-05-31 13:14 UTC, lmignon commented
@pierre-halleux Can you check this one PLZ?

2022-05-31 13:26 UTC, ThomasBinsfeld commented
@lmignon It looks like @pierre-halleux found another solution : https://github.com/acsone/alfodoo/commit/7d8d9ba824a576ffa8232c55629c979b704db1fb

2022-05-31 14:31 UTC, lmignon commented
@ThomasBinsfeld IMO, your fix is right. In your case you ensure that the record cache is cleaned up after the rollback.

2022-05-31 14:58 UTC, sbidoul commented on cmis_field/fields/cmis_folder.py
> +                    self.__set__(record, None)
That's a case where a comment explaining *why* is justified :)

2022-05-31 15:28 UTC, ThomasBinsfeld commented
Conflicts fixed and explanation added in inline comments.

2022-06-02 07:45 UTC, lmignon requested changes

2022-06-02 07:45 UTC, lmignon commented on cmis_field/fields/cmis_folder.py
> +                    _repo.getObject(cmis_object_id).deleteTree()
@ThomasBinsfeld We must also keep the previous code and comment

2022-11-06 12:03 UTC, closed without merging