[16.0][MIG] cmis_mail
acsone/alfodoo pull request #186
Opened 2023-12-21 11:03 UTC by benwillig

2024-01-02 10:26 UTC, FrancoMaxime approved these changes
LGTM: code review

2024-06-10 13:22 UTC, ThomasBinsfeld approved these changes

2024-08-22 15:06 UTC, glitchov requested changes, later dismissed

2024-08-22 15:06 UTC, glitchov commented on cmis_mail/wizards/mail_compose_message.py
> +        field_name = self.cmis_folder_field_id.name
Access to ir.model.fields that will cause an error if not sudo
```suggestion
        field_name = self.cmis_folder_field_id.sudo().name
```

2025-01-26 12:05 UTC, closed without merging

2025-11-26 08:38 UTC, ThomasBinsfeld commented
Reopened with fixes in #197